#!/bin/bash
#
# progname - short desciption
#
#    Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. If not, see <http://www.gnu.org/licenses/gpl.html>
#
# Long description
# ... that may span over multiple lines

usage() {
cat <<- USAGE
	Usage: $self [options]
USAGE
if [[ "$1" ]] ; then
	cat <<- USAGE
		Try '$self --help' for more information.
	USAGE
	exit 1
fi
cat <<-USAGE

	Short description

	Options:
	-h|--help     - show this page.
	-v|--verbose  - print more details about what is being done.

	Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
USAGE
exit 0
}
invalid() { echo "$self: $1" ; usage 1 ; }

self="${0##*/}"
verbose=0

# Loop options
while (( $# )); do
	case "$1" in
	-h|--help     ) usage                          ;;
	-v|--verbose  ) verbose=1                      ;;
	--            ) shift ; files=( "$@" ) ; break ;;
	-*            ) opts+=( "$1" )                 ;;
	*             ) shift ; files=( "$@" ) ; break ;;
	esac
	shift
done


