#!/usr/bin/php
<?php
$cpf = substr((empty($argv[1])?'':$argv[1]) . str_pad(rand(1, 999999998), 9, '0', STR_PAD_LEFT), 0, 9);
for ($t = 9; $t < 11; $t++) {
	for ($d = 0, $c = 0; $c < $t; $c++)
		$d += $cpf[$c] * (($t + 1) - $c);
	$cpf .= ((10 * $d) % 11) % 10;
}
echo $cpf."\n";
