#!/usr/bin/env python
import sys
import GeoIP

def main(argv=None):
    if argv is None:
        argv = sys.argv[1:]

    try:
        path = argv[0]
    except IndexError:
        print "Usage: geoip <FILE>"
        return

    geo = GeoIP.new(GeoIP.GEOIP_MEMORY_CACHE)
    with open(path) as fp:
        for line in fp:
            ip = line.strip()
            print "%s\t%s" % (geo.country_code_by_addr(ip),
                              geo.country_name_by_addr(ip),)

if __name__ == '__main__':
    sys.exit(main())
