#!/bin/bash
#
# Remove old kernels but keep the first, the current and the previous
#
#    Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

myname="${0##*/}"
verbose=1
keepfirst=1
keepprevious=1

message() { ((verbose)) && printf "%s\n" "$1"; }
argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
invalid() { argerr "invalid option: $1" ; }
usage() {
	cat <<-USAGE
	Usage: $myname [options]
	USAGE
	if [[ "$1" ]] ; then
		cat >&2 <<- USAGE
		Try '$myname --help' for more information.
		USAGE
		exit 1
	fi
	cat <<-USAGE

	Remove old kernels but keep the first, the current and the previous

	Options:
	  -h|--help     - show this page.
	  -q|--quiet    - do not print informative messages.

	  --remove-first    - also remove first kernel
	  --remove-previous - also remove previous kernel

	Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
	USAGE
	exit 0
}

for arg in "$@"; do [[ "$arg" == "-h" || "$arg" == "--help" ]] && usage ; done
while (( $# )); do
	case "$1" in
	-q|--quiet       ) verbose=0      ;;
	--remove-first   ) keepfirst=0    ;;
	--remove-previous) keepprevious=0 ;;
	-*) invalid "$1" ;;
	* ) argerr  "$1" ;;
	esac
	shift
done

export current=$(uname -r | cut -d- -f-2)
list=$(
	dpkg --list "linux-*" |
	grep -E "^ii  linux-(headers|image)-[2-5]\." |
	cut -d' ' -f3 |
	sort -V |
	grep -v "$current"
)

message "Removing all kernels but keeping:"

keep=()

if ((keepfirst)); then
	first=$(head -n 1 <<< "$list" | cut -d- -f3,4)
	keep+=(-e "$first")
	message "First   : $first"
fi
if ((keepprevious)); then
	previous=$(tail -n 1 <<< "$list" | cut -d- -f3,4)
	keep+=(-e "$previous")
	message "Previous: $previous"
fi

if ((${#keep[@]})); then
	keep+=(-v)
else
	keep=('')
fi

message "Current : $current"

sudo apt-get purge $(grep "${keep[@]}" <<< "$list") &&
message "Done, success!" ||
echo "Opps, something went wrong, better check the output!"
