#!/bin/bash

myname="${0##*/}"

usage() {
	msg="$1\nUsage: $myname <FILE|DIR> <FILE|DIR> [FILE|DIR]\n"
	if [[ "$TERM" == "dumb" ]] && type zenity >/dev/null 2>&1 ; then
		msg="${msg//&/&amp;}"
		msg="${msg//</&lt;}"
		zenity --info --no-wrap --text "$msg"
	else
		printf "%b" "$msg" >&2
	fi
	exit 1
}

md5sumdir() (
	cd "$1"
	find . -type f -exec md5sum {} + | LC_ALL=C sort -f --key=2
)

case $# in
	2|3)
		# set the trap with swapped quotes for delayed array evaluation
		trap 'rm -f -- "${items[@]}"' EXIT
		items=()

		while (( $# )) ; do
			#FIXME: Use mktemp instead of tempfile
			tempfile=$(tempfile --prefix "_" --suffix "_${1//\//_}")
			items+=( "$tempfile" )

			[[ -f "$1" ]] && hexdump -C "$1" > "$tempfile"
			[[ -d "$1" ]] && md5sumdir  "$1" > "$tempfile"
			shift
		done
	;;
	*) usage "$myname requires either 2 or 3 arguments";;
esac

meld "${items[@]}"
