#!/bin/bash

myname="${0##*/}"

usage() {
	msg="$1\nUsage: $myname <FILE|DIR> <FILE|DIR> [FILE|DIR]\n"
	if [[ "$TERM" == "dumb" ]] && type zenity >/dev/null 2>&1 ; then
		msg="${msg//&/&amp;}"
		msg="${msg//</&lt;}"
		zenity --info --no-wrap --text "$msg"
	else
		printf "%b" "$msg" >&2
	fi
	exit 1
}

md5sumdir() (
	cd "$1"
	find . -type f -exec md5sum {} + | LC_ALL=C sort -f --key=2
)

case $# in
	2|3)
		tempdir=$(mktemp -d) || exit 1
		trap 'rm -rf -- "$tempdir"' EXIT
		i=0

		{
		echo # to start pulsating zenity's progress bar
		while (( $# )) ; do
			tempfile="${tempdir}/$((++i)) ${1//\//_}"
			[[ -f "$1" ]] && hexdump -C "$1" > "$tempfile"
			[[ -d "$1" ]] && md5sumdir  "$1" > "$tempfile"
			shift
		done
		} |
		zenity --progress --pulsate --auto-close --auto-kill --title "$myname" \
		       --text "Comparing $*\n\nThis may take a long time.\n" \
		        >/dev/null 2>&1
	;;
	*) usage "$myname requires either 2 or 3 arguments";;
esac

meld "$tempdir"/*
