#!/bin/bash
#
# monitor-switch - switch outputs using xrand
#
#    Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>

declare -A monitor_opts
declare -a monitors

# Default settings
# TODO: source from a ~/.config file
monitors=(DFP10 DFP9)  # order matters: list them from left to right
monitor_opts[DFP9]="--mode 1920x1080 --rate 60"
#############

myname="${0##*/}"
verbose=0

# if there's no pre-defined monitors list, read from xrandr
if [[ -z "$monitors" ]]; then
	while read -r output ; do
		monitors+=("$output")
	done < <(xrandr | awk '$2 ~/^c/{print $1}' | sort)
fi

message() { printf "%s\n" "$1" >&2 ; }
fatal()   { [[ "$1" ]] && message "$myname: error: $1" ; exit ${2:-1} ; }
argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
invalid() { argerr "invalid argument: $1" ; }
missing() { argerr "missing ${2:+$2 }operand${1:+ from $1}." ; }

usage() {
	cat <<-USAGE
	Usage: $myname [options]
	USAGE
	if [[ "$1" ]] ; then
		cat >&2 <<- USAGE
		Try '$myname --help' for more information.
		USAGE
		exit 1
	fi
	cat <<-USAGE

	Switch monitors using xrandr.

	Options:
	  -h|--help          - show this page.
	  -v|--verbose       - print in terminal the full xrandr command executed.

	  -a|--all           - enable all monitors.
	  -s|--select OUTPUT - enable monitor OUTPUT, disable all others.
	  -l|--left          - enable leftmost monitor.  Alias for --select ${monitors[0]}
	  -r|--right         - enable rightmost monitor. Alias for --select ${monitors[${#monitors[@]}-1]}

	Copyright (C) 2012 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
	USAGE
	exit 0
}

# Option handling
for arg in "$@"; do [[ "$arg" == "-h" || "$arg" == "--help" ]] && usage ; done
while (( $# )); do
	case "$1" in
	-v|--verbose) verbose=1 ;;
	-q|--no-notify) notify=0 ;;
	-a|--all) all=1 ;;
	-s|--select) shift ; monitor="$1" ;;
	-l|--left )  xrandr --output DFP10 --off --output DFP9 --auto --mode 1920x1080 --rate 60 --primary ; all=1 ;;  # monitor="${monitors[0]}" ;;
	-r|--right)  xrandr --output DFP10 --auto --primary --output DFP9 --off ; all=1 ;;  # monitor="${monitors[${#monitors[@]}-1]}" ;;
	*) invalid "$1" ;;
	esac
	shift
done

# Loop outputs (monitors)
for output in "${monitors[@]}"; do
	if ((all)) || [[ "$output" = "$monitor" ]]; then
		xrandropts+=(--output "$output" --auto ${monitor_opts["$output"]})
		if ((all)); then
			if [[ "$output" = "${monitors[0]}" ]]; then
				xrandropts+=(--pos 0x0 --primary)
			else
				xrandropts+=(--right-of "$previous")
			fi
			previous="$output"
		else
			xrandropts+=(--primary)
		fi
	else
		xrandropts+=(--output "$output" --off)
	fi
done

((verbose)) && message "$myname: executing xrandr ${xrandropts[*]}"
xrandr "${xrandropts[@]}"
