#!/bin/bash

[[ "$1" ]] || {
	echo "Creates a new script from template."
	echo "Usage: newscript NAME"
	exit 1
} >&2

script="$SCRIPTS/$1"

cp "$SCRIPTS/reference/template" "$script"

xdg-open "$script"
