#!/bin/bash

# User input
keyid=$1
passfile=$2

# Tunables
sdelta=5
cdelta=2500
mode=0 # 0 for fixed counts, 1 for fixed seconds, else to disable feedback
log=$HOME/.passcrack.log

start=$(date +%s)
prev=$start
total=0
count=0
procs=0

crack() {
	gpg --default-key "$keyid" --passphrase "$1" --batch --dry-run \
		--no-use-agent --clearsign /dev/null >/dev/null 2>&1 &&
	{
		echo "Password found! :D \o/"
		printf "%s\t%s\t%s\n" "$(date +'%F %T')" "$keymsg" "$password" >> "$log"
		return 0
	}
	return 1
}

usage() { printf "%s\nUsage: passcrack <keyid> <password file>\n" "$1"; exit 1; }

[[ "$keyid" ]]       || usage "No key ID!"

keymsg=$(gpg --list-secret-keys --with-colons "$keyid" | head -n1)
feedback="%s: tried %d (%d passwords/sec). Total: %d, last: %s\n"

printf "Password Cracker\nCracking %s\nUsing %s\n" "$keymsg" "$passfile"
while read -r password; do

	crack "$password" && exit
	((count++))

	case "$mode" in
	0) # feedback every 'cdelta' tries. Fast, but hard to tune
		if (( count==cdelta )); then
			printf -v now '%(%s)T' -1 #now=$(date +%s)
			sdelta=$((now - prev))
			((total += count))
			printf "$feedback" "$(date +'%F %T')" "$count" "$((count/sdelta))" "$total" "$password"
			((prev = now, count = 0))
		fi
	;;
	1) # feedback every 'sdelta' seconds. Hardware-independent, but *very* slow
		printf -v now '%(%s)T' -1 # now=$(date +%s)
		if ((now - prev > sdelta)); then
			(( total+=count ))
			printf "$feedback" "$(date +'%F %T')" "$count" "$((count/sdelta))" "$total" "$password"
			((prev = now, count = 0))
		fi
	;;
	esac
done < "$passfile"

echo "Password not found :("
exit 2
