#!/bin/bash
#
# ssh-writes - show total bytes written from a device
#
# Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
# License: GPLv3 or later, at your choice. See <http://www.gnu.org/licenses/gpl>
#------------------------------------------------------------------------------

devices=("$@")

#------------------------------------------------------------------------------
myname=${0##*/}
usage() {
	if [[ "${1:-}" ]] ; then exec >&2; fi
	cat <<-USAGE
	Usage: $myname [-h|--help] [DEVICE...]
	USAGE
	if [[ "${1:-}" ]] ; then
		cat <<- USAGE
		Try '$myname --help' for more information.
		USAGE
		exit 1
	fi
	cat <<-USAGE

	Show total kbytes written in a partition

	Options:
	  -h|--help     - show this page.

	If no DEVICE is chosen, show all available devices. If device is a disk
	instead of a partition, show all partitions of that disk.

	Only works for mounted partitions that have an entry at /sys/fs/*/<DEV>,
	so usually limited to ext4 partitions.

	Copyright (C) 2022 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
	USAGE
	exit 0
}
for arg in "$@"; do [[ "$arg" == "-h" || "$arg" == "--help" ]] && usage ; done

devlist=$(
	udevadm settle  # sync info obtainable by the lsblk
	lsblk -pnlo NAME,FSTYPE,TYPE,MOUNTPOINT "${devices[@]}"
) || exit $?

now=$(date --rfc-3339=seconds)
epoch=$(date '+%s')
while read -r dev fs; do
	path=/sys/fs/${fs}/${dev##*/}/lifetime_write_kbytes
	if ! [[ -r "$path" ]]; then continue; fi
	bytes=$(( "$(< "$path")" * 1024 ))
	human=$(numfmt "$bytes" --to-unit=G  --format "%9.2f")G
	printf "${now}\t${epoch}\t${dev}\t${bytes}\t${human}\n"
done < <(awk '$3 == "part" && $2 && $4 {print $1 "\t" $2}' <<< "$devlist")

# for fdisk-list
# cols=TYPE,NAME,SIZE,FSTYPE,LABEL,PARTLABEL,UUID,PARTFLAGS,VENDOR,MODEL,REV,SERIAL
# lsblk --noheadings --list --bytes --exclude 7 --output "$cols"
