#!/bin/bash
#
# progname - short desciption
#
#    Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program. See <http://www.gnu.org/licenses/gpl.html>
#
# Long description
# ... that may span over multiple lines

myname="${0##*/}"
mydir=$(dirname "$(readlink -f "$0")")
verbose=0

shift="+00:00:00.700"

fatal()   { [[ "$1" ]] && echo "$myname: error: $1" >&2 ; exit ${2:-1} ; }
message() { ((verbose)) && printf "%s\n" "$1"; }
integer() { [[ "$1" != *[!0-9]* ]] || argerr "'$1'${2:+ in $2} is not an integer." ; }
skip()    { i=${2:-$file}; message "skipping${i:+ $i}${1:+: $1}"; continue ; }
argerr()  { printf "%s: %s\n" "$myname" "${1:-error}" >&2 ; usage 1 ; }
invalid() { argerr "invalid option: $1" ; }
missing() { argerr "missing ${2:+$2 }argument${1:+ from $1}." ; }
quit()    { message "Goodbye!" ; exit; }
relpath() { python -c "import os, sys; print os.path.relpath(*sys.argv[1:3])" "$@"; }


usage() {
	cat <<-USAGE
	Usage: $myname [options] FILE
	USAGE
	if [[ "$1" ]] ; then
		cat >&2 <<- USAGE
		Try '$myname --help' for more information.
		USAGE
		exit 1
	fi
	cat <<-USAGE

	Short description

	Options:
	  -h|--help     - show this page.
	  -v|--verbose  - print more details about what is being done.

	  --shift TIME  - how much TIME to shift, in HH:MM:SS.xxx format (Default: $shift)
	  --text  TEXT  - start shift from the line containing TEXT.
	                  If blank, start shift from the first line

	Copyright (C) 2013 Rodrigo Silva (MestreLion) <linux@rodrigosilva.com>
	License: GPLv3 or later. See <http://www.gnu.org/licenses/gpl.html>
	USAGE
	exit 0
}

# Option handling
files=()
for arg in "$@"; do [[ "$arg" == "-h" || "$arg" == "--help" ]] && usage ; done
while (( $# )); do
	case "$1" in
	-v|--verbose  ) verbose=1                      ;;
	--text=*      ) text="${1#*=}"                 ;;
	--text        ) shift ; text="$1"              ;;
	--shift=*     ) shift="${1#*=}"                ;;
	--shift       ) shift ; shift="$1"             ;;
	--            ) shift ; break                  ;;
	-*            ) invalid "$1"                   ;;
	*             ) [[ "$file" ]] && invalid "$1";
	                file="$1"                      ;;
	esac
	shift
done

[[ "$shift" ]] || missing "--shift" "NUM"
[[ "$file"  ]] || missing "FILE"

echo "var=$text"
echo "var=$shift"
echo "var=$file"

tempfile=$(mktemp) || fatal
trap 'rm -f -- "$tempfile"' EXIT

cp "$file" "$temp" || fatal
