#!/bin/bash


BASH_COMPLETION_DIR_USER="$SCRIPTS/home/bash_completion.d"

if [[ -d $BASH_COMPLETION_DIR_USER &&
      -r $BASH_COMPLETION_DIR_USER &&
      -x $BASH_COMPLETION_DIR_USER ]]; then
	for script in "$BASH_COMPLETION_DIR_USER"/*; do
		[[ ${script##*/} != @(*~|*.bak) &&
		   -f $script &&
		   -r $script ]] &&
			source "$script"
	done
fi
