# Commands meant to run at every shell
#
# To be sourced by ~/.bashrc
#
# To run, add these lines to ~/.bashrc:
#
#	if [ -f "$SCRIPTS/home/bashrc" ] ; then
#	    . "$SCRIPTS/home/bashrc"
#	fi

# Supporting Functions ---------------------------------------------------------

exists()  { type "$@" &>/dev/null; }
snipfile(){ local n="{${3:-5},}" s; s="/^# *>$n *${2:-}/"; awk "$s,/<$n/&&!$s" "$1"; }

# ------------------------------------------------------------------------------

source <(snipfile "$SCRIPTS/home/bash_aliases_min" 'XDG defs')
source <(snipfile "$SCRIPTS/home/bash_aliases_min" 'XDG bashrc')

# ------------------------------------------------------------------------------

# Enable bash-completion, if not already enabled by ~/.bashrc
if	[ -z "${BASH_COMPLETION_VERSINFO:-}" ] &&
	[ -f /usr/share/bash-completion/bash_completion ] &&
	! shopt -oq posix
then
	source /usr/share/bash-completion/bash_completion
fi

if [ -f "$SCRIPTS/home/bash_aliases" ] ; then
	source "$SCRIPTS/home/bash_aliases"
fi

if [ -f "$HOME/work/wine-tools/wine-tools-bashrc" ] ; then
	source "$HOME/work/wine-tools/wine-tools-bashrc"
fi

if [ -f "$HOME/work/dosbox/dosbox-tools/dosbox-bashrc" ] ; then
	source "$HOME/work/dosbox/dosbox-tools/dosbox-bashrc"
fi

# Settings ---------------------------------------------------------------------

source <(snipfile "$SCRIPTS/home/bash_aliases_min" 'PS1 customization')
source <(snipfile "$SCRIPTS/home/bash_aliases_min" 'Settings')

# Create core dump files on segmentation fault. File `core` at current process dir
#ulimit -c unlimited

# ------------------------------------------------------------------------------

source <(snipfile "$SCRIPTS/home/bash_aliases_min" 'Cleanup')

# So cute!
exists cowfortune && { cowfortune | { exists lolcat && lolcat || cat ; } } || :
