#!/bin/sh
#
# Commands meant to run at every login
#
# To be sourced by ~/.profile
#
# To run, add these lines to ~/.profile:
#
#	export SCRIPTS="/path/to/scripts"
#	if [ -f "$SCRIPTS/home/profile" ] ; then
#	    . "$SCRIPTS/home/profile"
#	fi
#
# And edit "/path/to/scripts" to the proper path (by default ~/work/scripts)
# Dont forget to un-comment the lines too.
#
# Notes:
#
#  #!/bin/sh is specified to enforce compliance with /etc/gdm/Xession,
#  which sources ~/.profile at login. Thus, bashisms are not allowed here.
#
#  If SCRIPTS environment variable is already set in ~/.profile, will be
#  respected here. If not, SCRIPTS will be set as either ~/work/scripts or
#  /home/dados/work/scripts, whichever exists.
#
##############################################################################

if [ -z "$SCRIPTS" ] ; then
	for root in {"$HOME",/home/dados}/work/scripts; do
		if [ -d "$root" ] ; then break; fi
	done
	export SCRIPTS=$root
	unset root
fi

##############################################################################

# Prepend folders to $PATH, avoiding duplicates
# Parameters: a single string, ':' separated, cointaining the folders to add
# This function breaks the string and check each folder to avoid duplicates
# Note that folders will be prepended in the *reverse* order
prepend_path()
{
	SAVED_IFS="$IFS"
	IFS=:
	for folder in $1 ; do
		if ! $( echo "$PATH" | tr ":" "\n" | grep -qx "$folder" ) ; then
			PATH=$folder:$PATH
		fi
	done
	IFS="$SAVED_IFS"
	unset folder
}

##############################################################################

# Add scripts bin and current folder to PATH
prepend_path "$HOME/.local/bin:$SCRIPTS:/usr/local/games"

export PATH

# Thousand separator in ls filesizes
# could also use ls -l --block-size="'1" as alias
export LS_BLOCK_SIZE="'1"

# Debian Development
export DEBFULLNAME="Rodrigo Silva"
export DEBEMAIL="debian@rodrigosilva.com"

#Python
export PYTHONWARNINGS=default  # re-enable DeprecationWarning's disabled in Python 2.7

# PyLint
export PYLINTHOME=${XDG_CACHE_HOME:-$HOME/.cache}/pylint
export PYLINTRC=${XDG_CONFIG_HOME:-$HOME/.config}/pylintrc

# Locales
export LANG="en_US.utf8"
export LANGUAGE="en_US:en"
export LC_MESSAGES="en_US.utf8"
#export LC_NUMERIC="pt_BR.utf8" # qt4 (and maybe others) unfortunately use this
#export LC_TIME="pt_BR.utf8"
#export LC_MONETARY="pt_BR.utf8"
#export LC_PAPER="pt_BR.utf8"
#export LC_MEASUREMENT="pt_BR.utf8"

# if running bash (interactive login shell)
if [ -n "$BASH_VERSION" ]; then
	if [ -f "$SCRIPTS/home/bashrc" ] ; then
		. "$SCRIPTS/home/bashrc"
	fi
fi
