#!/bin/bash

# Better icons for BOINC
# https://bugs.launchpad.net/bugs/1173622

url="http://boinc.berkeley.edu/trac/export/HEAD/boinc-v2/clientgui/res/BOINCGUIApp.ico"

# Alternate locations: upstream gitweb and debian packaging repo. Don't remove the quotes!
# "http://boinc.berkeley.edu/gitweb/?p=boinc-v2.git;a=blob;f=clientgui/res/BOINCGUIApp.ico;hb=HEAD"
# "http://anonscm.debian.org/gitweb/?p=pkg-boinc/boinc.git;a=blob;f=clientgui/res/BOINCGUIApp.ico;hb=HEAD"

# is boinc really installed?
desktop=/usr/share/applications/boinc-manager.desktop
[[ -f "$desktop" ]] || exit

# create temp dir, the right way
dir=$(mktemp -d) || exit 1
trap "rm -rf -- '$dir'" EXIT
cd "$dir"

# download and extract icons
wget "$url" && icotool --extract * || exit 1

# install each extracted icon
for icon in *.png; do
	size=$(identify -format '%w' "$icon")
	echo "Installing icon size $size"
	xdg-icon-resource install --noupdate --novendor --size "$size" \
		"$icon" boincmgr
done
xdg-icon-resource forceupdate

# use my wrapper, if installed
if type boinc-manager >/dev/null 2>&1; then
	exec=boinc-manager
else
	# do not use full path
	exec=boincmgr
fi

echo "Updating desktop file"
cp "$desktop" .
desktop-file-edit --set-icon=boincmgr --set-key=Exec --set-value="$exec" \
	"${desktop##*/}"
xdg-desktop-menu install --novendor "${desktop##*/}"
echo "Done!"
