#!/bin/bash -x

myname="${0##*/}"

if [ -z "$SCRIPTS" ] ; then
	for root in {"$HOME",/home/{dados,rodrigo}}{/work,}/scripts; do
		if [ -d "$root" ] ; then break; fi
	done
	[[ "$root" ]] || { echo "could not find scripts root"; exit 1; }
	SCRIPTS=$root
fi

# custom profile
if ! grep -q "\$SCRIPTS" ~/.profile ; then
	cat >> ~/.profile <<-_EOF_

		# Added by $myname
		export SCRIPTS=${SCRIPTS/$HOME/\$HOME}
		if [ -f "\$SCRIPTS/home/profile" ] ; then
		    . "\$SCRIPTS/home/profile"
		fi
	_EOF_
fi

# custom bashrc
if ! grep -q "\$SCRIPTS" ~/.bashrc ; then
	cat >> ~/.bashrc <<-_EOF_

		# Added by $myname
		if [ -f "\$SCRIPTS/home/bashrc" ] ; then
		    . "\$SCRIPTS/home/bashrc"
		fi
	_EOF_
fi

# personal bin
mkdir -p "$HOME/.local/bin"

# Nautilus-extensions
relpath(){ python -c "import os.path; print os.path.relpath('$1'${2:+,'$2'})"; }
original=$HOME/.gnome2/nautilus-scripts
custom=$SCRIPTS/nautilus-scripts
if ! [[ -h "$original" ]]; then
	mkdir -p "$original"
	rmdir "$original" &&
	ln -s "$(relpath "$custom" "$(dirname "$original")")" "$original"
fi
