#!/bin/bash -x

myname="${0##*/}"


if [[ ! -d "$1" ]]; then
	echo "Usage: $myname <scripts root>"
fi

SCRIPTS=$(readlink -f "$1")

# custom profile
if ! grep -q "\$SCRIPTS" ~/.profile 2>/dev/null ; then
	cat >> ~/.profile <<-_EOF_

		# Added by $myname
		export SCRIPTS=${SCRIPTS/$HOME/\$HOME}
		if [ -f "\$SCRIPTS/home/profile" ] ; then
		    . "\$SCRIPTS/home/profile"
		fi
	_EOF_
fi

# custom bashrc
if ! grep -q "\$SCRIPTS" ~/.bashrc 2>/dev/null ; then
	cat >> ~/.bashrc <<-_EOF_

		# Added by $myname
		if [ -f "\$SCRIPTS/home/bashrc" ] ; then
		    . "\$SCRIPTS/home/bashrc"
		fi
	_EOF_
fi

# custom bash_completion
if ! grep -q "\$SCRIPTS" ~/.bash_completion 2>/dev/null ; then
	cat >> ~/.bash_completion <<-_EOF_

		# Added by $myname
		if [ -f "\$SCRIPTS/home/bash_completion" ] ; then
		    . "\$SCRIPTS/home/bash_completion"
		fi
	_EOF_
fi


# personal bin
mkdir -p "$HOME/.local/bin"

# Nautilus-extensions
relpath(){ python -c "import os.path; print os.path.relpath('$1'${2:+,'$2'})"; }
original=$HOME/.gnome2/nautilus-scripts
custom=$SCRIPTS/nautilus-scripts
if ! [[ -h "$original" ]]; then
	mkdir -p "$original"
	rmdir "$original" &&
	ln -s "$(relpath "$custom" "$(dirname "$original")")" "$original"
fi

echo "NOW IN ~/.profile MANUALLY MOVE ENTRIES THAT SOURCES ~/.bashrc TO AFTER THE SOURCING OF $SCRIPTS/home/profile"
