#!/bin/bash

# disable "Chanserv gives voice to.." messages
# http://forums.linuxmint.com/viewtopic.php?f=42&t=50381

mkdir -p ~/.xchat2

cat > ~/.xchat2/voicekill.pl <<EOF
Xchat::register( "Hide Voice", "0.1" );
Xchat::hook_print( "Channel Voice", sub { return Xchat::EAT_XCHAT });
EOF

