#!/bin/bash -x

#PATH=${PATH}:/dados/progs/linux/runonce/mint10:/dados/progs/linux/runonce/setup

if [ -z "$SCRIPTS" ] ; then
	for root in {"$HOME",/home/dados}/work/scripts; do
		if [ -d "$root" ] ; then break; fi
	done
	export SCRIPTS=$root
	unset root
fi

dir="$SCRIPTS/runonce/ubuntu1204"
scripts=( "${dir}"/* )

for script in "${scripts[@]}" ; do

	filename="${script##*/}"
	[[ "$filename" != runonce_* && "$filename" != *.undo ]] && echo "${script}"

done

# GTK BOOKMARKS!
# gedit settings (PLUGINS!!!)
# screen resolution and drivers

# Enable repos
# Add PPAs
# Install software
sudo apt-get install gedit-plugins

# Symlinks to /dados
# Grub customization
# Nautilus Settings
# sudo dwww-index++

# keyboard shortcuts for rotate monitor
# keyboard delay and speed

# Wine Fix
wget https://launchpad.net/~jcollins/+archive/jaminppa/+build/1482994/+files/getlibs_2.06-0ubuntu1%7Eppa2_all.deb
sudo dpkg -i getlibs_2.06-0ubuntu1~ppa2_all.deb
sudo ln -s /usr/lib/i386-linux-gnu /usr/lib32
sudo getlibs -p gnome-keyring:i386
sudo mkdir -p /usr/lib/i386-linux-gnu/pkcs11
sudo ln -s /usr/lib32/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so /usr/lib/i386-linux-gnu/pkcs11/gnome-keyring-pkcs11.so
sudo apt-get remove --purge getlibs
rm getlibs_2.06-0ubuntu1~ppa2_all.deb
