#!/bin/bash
#
# lib/common - library of common functions used in my personal scripts
#
#    Copyright (C) 2011 Rodrigo Silva - <linux@rodrigosilva.com>
#
#    This program is free software: you can redistribute it and/or modify
#    it under the terms of the GNU General Public License as published by
#    the Free Software Foundation, either version 3 of the License, or
#    (at your option) any later version.
#
#    This program is distributed in the hope that it will be useful,
#    but WITHOUT ANY WARRANTY; without even the implied warranty of
#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#    GNU General Public License for more details.
#
#    You should have received a copy of the GNU General Public License
#    along with this program.  If not, see <http://www.gnu.org/licenses/>.


exec 3> /dev/null # to avoid harcoding /dev/null everywhere. For tools' stderr.


# _TestRequirements() { #TODO }

exists()
{
	type "$1" >/dev/null 2>&1;
}

required()
{
	local cmd=$1
	local msg=${2:-Missing required command: $cmd}
	if ! exists "$cmd"; then
		fatal "$msg"
	fi
}

testroot()
{
	# simple root test
	[[ "$(id -u)" -eq 0 ]] || fatal "You must run this as root"
}

confirm()
{
	# For both default parameter and user input,
	# non-empty garbage will always evaluate to and behave as NO
	local message=${1:-"Confirm?"}
	local default=${2:-n}
	local silentno=${3:-0}

	local question="NO"
	if [[ "$default" == "y" ]]; then question="YES"; fi

	if ! ((yes)); then
		read -p "$message (y/n, default $question): " confirm
		confirm="${confirm:-$default}"
		case "$confirm" in
		[Yy]*) ;;
		*    ) if ! ((silentno)); then echo "cancelled by user"; fi
		       return 2
		       ;;
		esac
	fi
	return 0
}

fatal()
{
	local message="$1"
	local errorcode="${2:-1}"
	local dump="$3"

	if [[ "$dump"    ]]; then printf "%s\n" "$dump" >&2; fi
	if [[ "$message" ]]; then
		printf "%s\n" "${0##*/}: error: $message" >&2
	fi

	exit $errorcode
}

fatalgui()
{
	local msg="${1:-}"
	local errorcode="${2:-1}"
	local dump="$3"

	# Not a true "HTMLencode" but should cover most cases...
	local message="${msg:-Error on execution!}"
	message="${message//&/&amp;}"
	message="${message//</&lt;}"
	message="${message//>/&gt;}"

	zenity --error --title="${0##*/}" \
	       --text="${message:+$message\n\n}${dump:+$dump\n\n}"
	             #"Exiting with error code ${errorcode}"

	# Also output original message
	fatal "$msg" "$errorcode" "$dump"
}

min() { (( $1 < $2 )) && printf "%d" "$1" || printf "%d" "$2"; }
max() { (( $1 > $2 )) && printf "%d" "$1" || printf "%d" "$2"; }

trim() { read -r var <<< "$1"; printf "%s" "$var"; }

debug()
{
	local var="$1"
	declare -p var
	exit
}

xdg-data-list()
{
	local path="$1"
	local user
	local system
	local folder
	local list=()

	IFS=: read -ra system <<< "${XDG_DATA_DIRS:-/usr/local/share/:/usr/share/}"

	for folder in "${system[@]}" ; do
		if [[ -e "$folder/$path" ]] ; then
			list+=("${folder%/}/$path")
		fi
	done

	user="${XDG_DATA_HOME:-$HOME/.local/share}/$path"
	[[ -e "$user" ]] && list+=("$user")

	xdg_data_list_RESULT=("${list[@]}")
}

xdg-data-cat()
{
	local path="$1"

	xdg-data-list "$path"
	cat "${xdg_data_list_RESULT[@]}"
	unset xdg_data_list_RESULT
}

# emulate sed's --in-place for commands that lack it, such as awk
# Usage: inplace <command> [cmdargs...] -- FILE(s)...
# Note the the mandatory '--' to separate the command from list of files!
# Command will be executed multiple times as '<command> [cmdargs...] -- <FILE>',
#   and it must output to stdin for inplace() to work correctly.
# Directories and non-existing files will be skipped with a warning in stderr
inplace() {
	local cmd=()
	local outfile
	local tmpfile

	while (( $# )); do
		case "$1" in
		--) shift; break;;
		*) cmd+=( "$1" );;
		esac
		shift
	done

	if ! (( $# && ${#cmd[@]} )); then
		fatal "usage: inplace <command> [cmdargs...] -- FILE(s)..."
	fi

	for outfile; do
		if [[ -d "$outfile" ]]; then
			echo "Is a directory: $outfile" >&2
			continue
		elif ! [[ -f "$outfile" ]]; then
			echo "No such file: $outfile" >&2
			continue
		fi

		tmpfile=$(mktemp) || fatal
		trap 'rm -f -- "$tmpfile"' EXIT

		"${cmd[@]}" -- "$outfile" > "$tmpfile" && {
		chmod --reference "$outfile" "$tmpfile" # preserve permissions, GNU-only
		mv "$tmpfile" -- "$outfile"; }
	done
}

unzip_toplevels() {
	unzip -l "$1" |
	sed 's/^[^:]*:..   //' |
	egrep -o '^[^/]+/?' |
	LC_ALL=C uniq |
	tail -n +4 |
	head -n -2
}

msg_gui() {
	msg=$*
	if [[ "$TERM" == "dumb" ]] && type zenity >/dev/null 2>&1 ; then
		msg="${msg//&/&amp;}"
		msg="${msg//</&lt;}"
		zenity --info --no-wrap --text "$msg"
	else
		printf "%b" "$msg" >&2
	fi
}

# see bash_aliases_min for an extended 3-functions version
install_packages() {
	# Avoid marking installed packages as manual by only installing missing ones
	local pkg=
	local pkgs=()
	local ok
	for pkg in "$@"; do
		# shellcheck disable=SC1083
		ok=$(dpkg-query --showformat=\${Version} --show "$pkg" 2>/dev/null || true)
		if [[ -z "$ok" ]]; then pkgs+=( "$pkg" ); fi
	done
	if (("${#pkgs[@]}")); then
		sudo apt install "${pkgs[@]}"
	fi
}
