#!/bin/bash

# Answer to:
# http://stackoverflow.com/questions/10500521/linux-retrieve-monitor-names

# Inspired by:
#xrandr --verbose | perl -ne '
#if ((/EDID_DATA:/.../:/) && !/:/) {
#  s/^\s+//;
#  chomp;
#  $hex .= $_;
#} elsif ($hex) {
#  open FH, "|strings|head -n4|tail -n1";
#  print FH pack("H*", $hex);
#  $hex = "";
#}'

xrandr --verbose | awk '
/[:.]/ && hex {
	sub(/.*000000fc00/, "", hex)
	hex = substr(hex, 0, 26) "0a"
	sub(/0a.*/, "0a", hex)
	print hex
	hex=""
}
hex {
	gsub(/[ \t]+/, "")
	hex = hex $0
}
/EDID.*:/ {
	hex=" "
}' | xxd -r -p
