#!/usr/bin/env bash
# https://gist.github.com/3911059

${BASH_VERSION+shopt -s lastpipe extglob}

if [[ -v .sh.version ]]; then
    builtin getconf
    function BASHPID.get {
        read -r .sh.value _ </proc/self/stat
    }
fi

function f {
    printf '%d: sleeping %d sec\n' "${@:1:2}" >&2
    sleep "$2"

    printf '%d: returning %d\n' "$1" "$3" >&2
    return "$3"
}

typeset -i n j maxj=$(getconf _NPROCESSORS_ONLN)

set -m
trap '((j--))' CHLD

for ((n=0;n++<30;)); do
    f "$BASHPID" $(((RANDOM%3)+1)) $((RANDOM%2)) &
    echo "j=$j"
    ((++j >= maxj)) && POSIXLY_CORRECT= wait
done

echo 'finished, waiting for remaining jobs...' >&2
trap - CHLD
wait

# vim: set fenc=utf-8 ff=unix ts=4 sts=4 sw=4 ft=sh nowrap et:
