#!/bin/bash

commonlib=$SCRIPTS/reference/commonlib
if [[ -f "$commonlib" ]]; then
	source "$commonlib"
else
	# This is a *nautilus* script, so we can assume GUI and zenity
	zenity --error --text "Required commonlib not found. Is \$SCRIPTS set?"
	exit
fi

formatjson() {
	local bsort=$1
	local infile=$2
	local INDENT=1
	if [[ "$infile" == '--' ]]; then
		infile=$3
	fi
	set -o pipefail
	{
	python - "$bsort" "$infile" <<-EOF
		import json
		import sys
		import collections

		bsort   = bool(int(sys.argv[1])) if len(sys.argv) > 1 else False
		infile  = sys.argv[2]            if len(sys.argv) > 2 else None

		if infile and not infile == "-":
		    with open(infile, "r") as fd:
		        data = json.load(
		            fd,
		            strict=False,
		            object_pairs_hook=collections.OrderedDict)
		else:
		    data = json.load(sys.stdin,
		                     strict=False,
		                     object_pairs_hook=collections.OrderedDict)

		json.dump(
		    data,
		    sys.stdout,
		    sort_keys=bsort,
		    indent=$INDENT,
		    separators=(",",": ")
		)
	EOF
	} |
	unexpand --tabs="$INDENT" --first-only |
	sed 's/^\t//'
}

files=()
bsort=0
while (( $# )); do
	case "$1" in
	--sort) bsort=1;;
	--) shift; break;;
	*) files+=( "$1" );;
	esac
	shift || break
done
files+=( "$@" )

result=$(inplace formatjson "$bsort" -- "${files[@]}" 2>&1)
if [[ "$result" ]]; then
	#zenity --error --title "Errors were found" --text "$result"
	fatalgui "$result"
	exit 1
fi
