#!/bin/bash
_winebottles()
{
        local cur

        COMPREPLY=()
        cur=${COMP_WORDS[COMP_CWORD]}
        COMPREPLY=($( compgen -W "$(for x in "$WINEBOTTLEHOME"/*; do [[ -d "$x" ]] && echo $(basename "$x"); done)" -- $cur ) )
}
complete -F _winebottles wine-delete wine-cmd wine-install wine-cd
