#!/bin/bash

die() { echo "$1" ; exit 1; }

CreateTempFile() 
{
	# See if this was called before
	if [[ "$tempfile" ]]; then
		# "push" previous file to end of array
		tempfile+=( "$tempfile" )
	else
		# set the trap
		trap 'echo deleting "${tempfile[@]}"' EXIT
	fi
	
	# set new file
	tempfile=$(tempfile) || die "could not create temporary file"	
}

subshell()
{
	exec 3>&1 1>&2
	
	echo "inside subshell"

	local tempfile
	declare -p tempfile
	
	echo "temp in subshell"; CreateTempFile 1; echo "subtmp=$tempfile"

	echo "result" >&3	
	echo "leaving subshell"
}

echo "1st temp"; CreateTempFile; echo "tmp1=$tempfile"
echo "2nd temp"; CreateTempFile; echo "tmp2=$tempfile"
echo "before subshell:"
declare -p tempfile
echo "invoking sub"; a="aaa-$(subshell)-bbb"; echo "a=$a"
echo "3rd temp"; CreateTempFile; echo "tmp3=$tempfile"
echo "4th temp"; CreateTempFile; echo "tmp4=$tempfile"

echo "end"

