#! /bin/bash

# Fix the following WARNING in ~/.xsession-errors
# gnome-session[2035]: EggSMClient-WARNING: Desktop file '/home/rodrigo/.config/autostart/skype.desktop' has malformed Icon key 'skype.png'(should not include extension)

system=1
sysfile="/usr/share/applications/skype.desktop"

[[ -f "$sysfile" ]] || {
	echo "Skype not installed (yet...)"
	exit
}

if ((system)) ; then
	file=$sysfile
	sudo=sudo
else
	file="$HOME/.local/share/applications/skype.desktop"
	mkdir -p "$(dirname "$file")"
	cp "$sysfile" "$file"
	sudo=env
fi

if cat "$file" | grep "^Icon=" | grep -q "\.png" ; then
	$sudo sed -i.bak '/^Icon=/s/\.png$//' "$file"
else
	echo "Nothing to fix! (maybe fixed already?)"
fi
